// AUTO-GENERATED by extract_frames.py
const TOTAL_FRAMES = 480;
const FRAMES_FOLDER = '_frames/sequence';
const SECTIONS = [
  { video:'assets/helmet-assembly.mp4', start:1, end:80 },
  { video:'assets/arc-reactor.mp4', start:81, end:180 },
  { video:'assets/chest-plate.mp4', start:181, end:280 },
  { video:'assets/gauntlet.mp4', start:281, end:360 },
  { video:'assets/full-suit.mp4', start:361, end:480 },
];
